In [1]:
import yfinance as yf 
import pandas as pd

In [12]:
df = yf.download("SPY", start="2010-01-01", end="2025-12-31", interval="1d")

[*********************100%***********************]  1 of 1 completed

In [13]:
df.columns = df.columns.droplevel(1)
df.head()

Price           Close       High        Low       Open     Volume
Date
2010-01-04  85.027924  85.072938  83.662435  84.307667  118944600
2010-01-05  85.253029  85.290545  84.667820  84.975433  111579900
2010-01-06  85.313057  85.523131  85.102983  85.170504  116074400
2010-01-07  85.673164  85.778202  84.915392  85.155477  131091100
2010-01-08  85.958290  85.995806  85.275549  85.448107  126402800

In [15]:
df.tail()

Price            Close        High         Low        Open    Volume
Date
2025-12-23  687.960022  688.200012  683.869995  683.919983  64840000
2025-12-24  690.380005  690.830017  687.799988  687.950012  39445600
2025-12-26  690.309998  691.659973  689.270020  690.640015  41613300
2025-12-29  687.849976  689.200012  686.070007  687.539978  62559500
2025-12-30  687.010010  688.559998  686.580017  687.450012  47160700

In [14]:
df.columns

Index(['Close', 'High', 'Low', 'Open', 'Volume'], dtype='str', name='Price')

In [16]:
df.isnull().sum()

Price
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [18]:
df.to_csv("data/spy_2010_2025.csv")